import { Link, useRevalidator } from 'react-router';
import { useEffect, useState } from 'react';
import type { Route } from './+types/research';
import type { ResearchOverview, ResearchDetail, ResearchBrief } from '@aihot/contracts/research';
import { adminGet } from '../../lib/admin.server';
export async function loader({request}:Route.LoaderArgs) {
 const id=new URL(request.url).searchParams.get('target');
 const [overview,me,detail]=await Promise.all([adminGet<ResearchOverview>(request,'/api/admin/research'),adminGet<{csrf:string}>(request,'/api/admin/me'),id?adminGet<ResearchDetail>(request,`/api/admin/research/targets/${encodeURIComponent(id)}`):Promise.resolve(null)]);
 return {overview,me,detail};
}
export const headers:Route.HeadersFunction=()=>({'Cache-Control':'private, no-store','Vary':'Cookie','X-Robots-Tag':'noindex, nofollow'});
export const meta:Route.MetaFunction=()=>[{title:'私人研究 · Research Desk（工作名）'},{name:'robots',content:'noindex, nofollow'}];
const time=(s:string|null)=>s?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short',timeZone:'Pacific/Auckland'}).format(new Date(s)):'未知';
function BriefView({brief}:{brief:ResearchBrief}) {
 return <article className="my-4 rounded-xl border border-line bg-surface p-5"><p className="text-sm text-ink-3">{brief.mode} · {time(brief.created_at)} · 目标版本 {brief.target_version}</p>
 <h3 className="mt-2 text-lg font-semibold">相对上次的变化</h3><ul>{brief.output.changes.length?brief.output.changes.map((s,i)=><li key={i}>{s}</li>):<li>输入版本没有新增变化；请同时检查任务与来源状态。</li>}</ul>
 {(['findings','alternatives'] as const).map(k=><section key={k}><h4 className="mt-4 font-semibold">{k==='findings'?'事实与关联建议':'相反解释与反例'}</h4>{brief.output[k].map((f,i)=><div className="my-3" key={i}><p>{f.text} <small>（{f.relation} / {f.assumption?'假设':'机器建议，待确认'}）</small></p>{f.citations.map(c=><blockquote key={c.evidenceId+c.quote} className="border-l-2 border-line pl-3 text-sm text-ink-3"><a href={`#evidence-${c.evidenceId}`}>证据版本 {c.evidenceId.slice(0,8)}</a>：{c.quote}</blockquote>)}</div>)}</section>)}
 {(['conflicts','unknowns','nextChecks'] as const).map((k)=><section key={k}><h4 className="mt-4 font-semibold">{{conflicts:'冲突',unknowns:'未知与覆盖缺口',nextChecks:'下次验证'}[k]}</h4><ul>{brief.output[k].map((s,i)=><li key={i}>{s}</li>)}</ul></section>)}
 </article>;
}
export default function Research({loaderData}:Route.ComponentProps) {
 const {overview,me,detail}=loaderData;const refresh=useRevalidator();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!overview.runs.some(r=>['queued','running'].includes(r.status)))return;const id=setInterval(()=>refresh.revalidate(),5000);return()=>clearInterval(id);},[overview.runs,refresh]);
 async function post(path:string,body:unknown={}) {setBusy(true);setMessage('');try {const res=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':me.csrf},body:JSON.stringify(body)});if(!res.ok)throw new Error(`操作失败（${res.status}）`);await refresh.revalidate();}catch(e){setMessage(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 return <div className="mx-auto max-w-5xl px-5 py-8 text-ink"><h1 className="text-2xl font-semibold">私人研究工作台</h1><p className="mt-2 text-ink-3">政治 / 宏观 / BTC / 美股 / AI / 创业 idea。工作名与预设可编辑；问题即入口，假设可选。Pacific/Auckland 显示时间。</p>
 <p className="my-3 rounded-lg bg-bg-sunk p-3 text-sm">覆盖：{Object.entries(overview.capabilities).map(([k,v])=>`${k}: ${v}`).join(' · ')}。真实 API 默认关闭，模拟分析不证明模型质量。</p>
 {message&&<p role="alert">{message}</p>}
 <div className="grid gap-6 md:grid-cols-2"><section><h2 className="text-xl font-semibold">变化雷达</h2>{overview.radar.length?overview.radar.map(b=><div className="my-3 rounded-lg border border-line p-3" key={b.id}><Link to={`?target=${b.target_id}`}>{b.question}</Link><p className="text-sm text-ink-3">{b.mode} · {time(b.created_at)}</p><p>{b.output.changes[0]??'无新增输入'}</p></div>):<p className="my-3">尚无成功简报；不能把未配置或来源失败解释为“无变化”。</p>}<h3 className="mt-4 font-semibold">探索资料（无需先建研究）</h3>{overview.exploration.map(e=><p className="my-2 text-sm" key={e.id}><a href={e.url} rel="noreferrer" target="_blank">{e.title}</a> · {e.mode==='demo'?'合成演示':'接入资料'} · {e.previous_id?'资料修订':'首次取得'} {time(e.available_at)}</p>)}<h3 className="mt-4 font-semibold">来源覆盖 / 健康</h3>{overview.sourceHealth.map(s=><p className="my-2 text-sm" key={s.id}>{s.name} · {s.health} · 最近抓取 {time(s.last_fetch_at)} · 最近成功 {time(s.last_ok_at)} · 失败 {s.fail_count}</p>)}<p className="text-sm">UNKNOWN 材料保留，召回不受公开精选分数限制。自动研究每五分钟检查已接入资料；开放搜索未配置。</p>{overview.coverage.map(c=><p key={c.source+c.mode} className="my-2 text-sm">{c.source} · {c.mode==='demo'?'合成演示':'接入资料'} · {c.versions} 版本 · 最后取得 {time(c.last_success)}</p>)}</section>
 <section><h2 className="text-xl font-semibold">我的研究</h2><form className="my-3 space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('/api/admin/research/targets',{question:f.get('question'),domain:f.get('domain'),hypothesis:f.get('hypothesis')||undefined,publicTerms:String(f.get('publicTerms')??'').split(',').map(s=>s.trim()).filter(Boolean)});}}><label className="block">问题 / 公司 / 资产 / idea<input className="block w-full rounded border border-line bg-surface p-2" name="question" required maxLength={600}/></label><label className="block">领域<select name="domain" className="ml-2 rounded border border-line bg-surface p-2">{[['unknown','探索'],['politics','政治'],['macro','宏观'],['btc','BTC'],['stocks','美股'],['ai','AI'],['ideas','创业 idea']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="block">假设（可选）<textarea name="hypothesis" maxLength={1200} className="block w-full rounded border border-line bg-surface p-2"/></label><label className="block">允许公开搜索的关键词（可选，用逗号分隔；仅此字段会外发）<input name="publicTerms" maxLength={300} className="block w-full rounded border border-line bg-surface p-2"/></label><button disabled={busy} className="rounded bg-ink px-4 py-2 text-bg">开始研究</button></form>{overview.targets.map(t=><p className="my-2" key={t.id}><Link className="underline" to={`?target=${t.id}`}>{t.question}</Link> · {t.domain}</p>)}</section></div>
 <section className="mt-6"><h2 className="text-xl font-semibold">任务状态</h2>{overview.runs.slice(0,8).map(r=><div key={r.id} className="my-2 flex flex-wrap gap-3 rounded border border-line p-3"><span>{r.status} · {r.calls}/{r.max_calls} 调用 · {r.stop_reason??'—'}</span>{['queued','running'].includes(r.status)&&<button disabled={busy} onClick={()=>void post(`/api/admin/research/runs/${r.id}/cancel`)}>取消</button>}{['failed','not_configured'].includes(r.status)&&<button disabled={busy} onClick={()=>void post(`/api/admin/research/runs/${r.id}/retry`)}>重试（保留原预算）</button>}<span className="text-sm">{r.steps.map(s=>`${s.step}: ${s.status}`).join(' / ')}</span></div>)}</section>
 {detail&&<section className="mt-8 border-t border-line pt-6"><h2 className="text-2xl font-semibold">{detail.target.question}</h2><p>可选假设：{detail.target.hypothesis??'未填写'}</p><div className="my-3 flex gap-4"><button disabled={busy} onClick={()=>void post(`/api/admin/research/targets/${detail.target.id}/run`)}>检查新资料</button><a href={`/api/admin/research/targets/${detail.target.id}/export`}>导出 JSON</a><a href={`/api/admin/research/targets/${detail.target.id}/export?format=markdown`}>导出 Markdown</a></div>{detail.briefs.map(b=><div key={b.id}><BriefView brief={b}/><div className="flex gap-4">{[['confirm','确认'],['correct','修正'],['ignore','忽略'],['result','追加结果']].map(([v,l])=><button disabled={busy} key={v} onClick={()=>{const note=window.prompt(`${l}：备注（可选）`);if(note!==null)void post(`/api/admin/research/targets/${detail.target.id}/actions`,{action:v,briefId:b.id,note});}}>{l}</button>)}</div></div>)}<h3 className="mt-6 text-xl font-semibold">证据账本</h3>{detail.evidence.map(e=><details id={`evidence-${e.id}`} key={e.id} className="my-3 rounded border border-line p-3"><summary>{e.title} · {e.mode==='demo'?'合成演示':'真实来源'}</summary><a className="underline" href={e.url} target="_blank" rel="noreferrer">原文出处</a><p className="text-sm">发布：{e.time_precision==='day'?e.published_at?.slice(0,10)??'未知':time(e.published_at)} · 精度 {e.time_precision} · 取得 {time(e.available_at)} · 版本 {e.id} · 修订自 {e.previous_id??'—'}</p><pre className="whitespace-pre-wrap text-sm">{e.body}</pre>{e.claims.map((c,i)=><p key={i}>[{c.kind}] {c.text} · 数值 {c.value??'未知'} {c.unit??''} / {c.period??'期间未知'} · 共识 {c.consensusSource?c.consensus??'未知':'未知（无来源）'}</p>)}</details>)}<h3 className="mt-6 font-semibold">反馈与结果（追加历史）</h3>{detail.actions.map(a=><p key={a.id}>{time(a.created_at)} · {a.action} · {a.note??'无备注'}</p>)}</section>}
 </div>;
}
